name: teste

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: workflow commands logging messages
        run: |
          echo "::debug::This is a debug message"
          echo "This is an info message"
          echo "::error::This is an error message"
          echo "::warning::This is a warning message"